[package]
name = "common"
version = "0.1.0"
authors = ["Daniel Graczer <daniel@fleek.co>"]
edition = "2018"

[dependencies]
ic-kit = "0.4.2"
ic-cdk = "0.3.1"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"
