name: PR Test runner

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/psychedelic/dank-explorer-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.PRIVATE_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Rust toolchain
        run: .github/scripts/rust-toolchain.sh

      - name: Target clean cache
        id: target-clean-cache
        uses: actions/cache@v2
        with:
          path: .github/target_clean
          key: cache-${{ runner.os }}-target-clean-cache-${{ hashFiles('.github/target_clean') }}

      - name: Target dir cache
        id: target-dir-cache
        uses: actions/cache@v2
        with:
          path: target
          key: cache-${{ runner.os }}-target-dir-cache-${{ hashFiles('cargo.lock') }}

      - name: Target dir clean
        if: steps.target-dir-cache.outputs.cache-hit != 'true' || steps.target-clean-cache.outputs.cache-hit != 'true'
        run: cargo clean

      - name: Test runner
        run: cargo test
